# -*- coding: utf-8 -*-
"""Chapter day: no figures (generated by engine/week_pack.py)."""
import pathlib, sys


def build(out_dir):
    pathlib.Path(out_dir).mkdir(parents=True, exist_ok=True)


if __name__ == '__main__':
    build(sys.argv[1])
