# -*- coding: utf-8 -*-
"""Sunday of the weekly plan (DL-10): no new authoring. The pack points to the week's library chapter
and lists what Monday–Saturday will add, so it is generated from plan/weeks.json."""
import json
from .paths import DAYS, PAPERS
from . import codes, plan


def paper_title(pid):
    p = PAPERS / f"{pid}.json"
    return json.loads(p.read_text(encoding="utf-8"))["paper"]["title"]["en"] if p.exists() else pid


def write_chapter_day(date, info):
    content = chapter_day(date, info)
    d = DAYS / date
    d.mkdir(parents=True, exist_ok=True)
    (d / "content.json").write_text(json.dumps(content, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    (d / "figures.py").write_text('# -*- coding: utf-8 -*-\n"""Chapter day: no figures (generated by engine/week_pack.py)."""\nimport pathlib, sys\n\n\n'
                                  "def build(out_dir):\n    pathlib.Path(out_dir).mkdir(parents=True, exist_ok=True)\n\n\n"
                                  "if __name__ == '__main__':\n    build(sys.argv[1])\n", encoding="utf-8")
    return d / "content.json"


def chapter_day(date, info):
    name = info["chapterName"]
    zh = name.split(" ")[0]
    days = info.get("days")
    rows = []
    if isinstance(days, dict):
        for d in sorted(days):
            for group in ("new", "consolidate"):
                for e in days[d].get(group, []):
                    rows.append(f"<tr><th>{d} {plan.weekday_zh(d)}</th><td>{'新' if group == 'new' else '夯实'} · {codes.name(e['type'])}</td>"
                                f"<td>{'、'.join(paper_title(i) if e['type'] == 'N-5' else i for i in e['items'])}</td><td>{'、'.join(codes.name(f) for f in e['forms'])}</td></tr>")
    week_html = ('<div class="table-scroll"><table class="summary-table"><thead><tr><th>日期</th><th>内容</th><th>条目</th><th>形式</th></tr></thead><tbody>'
                 + "".join(rows) + "</tbody></table></div>") if rows else '<p lang="zh-Hans">本周每天的条目还没排，等本章结构清单定好后写进 plan/weeks.json。</p>'
    week_md = "\n".join(r.replace("<tr><th>", "- ").replace("</th><td>", "：").replace("</td><td>", " · ").replace("</td></tr>", "") for r in rows) or "本周每天的条目还没排。"
    content = {
        "schema": "dpt-daily-pack/2", "date": date, "kind": "chapter_day", "week": info["week"], "chapter": info["chapter"], "chapter_name": name,
        "slug_zh": f"章节日-{zh}", "title": {"zh": f"本周章节：{zh}", "en": f"This week's chapter: {name.split(' ', 1)[-1]}"},
        "description": f"DPT 基础 · 第 {info['week']} 周章节日：先学完{zh}这一章，周一到周六每日推送补全。",
        "today_line": f"今天学完本周章节「{zh}」（五部分：解剖、神经、动作、临床解剖、复习）；周一到周六每天补新内容并夯实旧内容。",
        "study_plan": [["读章节", "解剖 → 神经 → 动作 → 临床解剖 → 复习，五部分一次读完"], ["做章末自测", "复习部分的问答先说再展开"],
                       ["看本周安排", "下面的表是周一到周六每天补什么、用什么形式"]],
        "tags": {"vertical": ["解剖学"], "horizontal": ["每周章节"]},
        "figures": {}, "sources": [],
        "chapters": [{"num": 1, "id": "chapter", "title": ["This week's chapter", "本周章节"], "toc": ["Chapter", "本周章节"],
                      "goals": [["Read all five parts of the chapter and answer its review questions.", "读完本章五部分，答完复习部分的问题。"],
                                ["Know what each day of the week will add.", "知道这一周每天会补什么。"]],
                      "terms": [],
                      "blocks": [{"t": "p", "en": "Sunday is chapter day: the whole week builds on this one chapter.",
                                  "zh": "周日是章节日：这一周的每日推送都围绕这一章。"},
                                 {"t": "chapter_link"},
                                 {"t": "h3", "en": "This week", "zh": "本周安排"},
                                 {"t": "html", "html": week_html, "md": week_md + "\n"}]}],
    }
    return content
